[package]
name = "mm_nes"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.22", features = ["max_level_debug", "release_max_level_info"] }
simplelog = { version = "0.12.2" }
once_cell = "1.19.0"
lazy_static = "1.5.0"

